apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  releaseName: autoscaler
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: kube-system
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
