apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      # 4.x switches to 1.x which is k8s > 1.19
      version: ">=3.0.0 <4.0.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: kube-system
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
