---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: "1.18"
  url: https://github.com/apenney/k8s-core.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/aws
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cloud/aws
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: ConfigMap
        name: release
