apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aws
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: release
  path: ./cloud/aws
  prune: true
  validation: server
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: release
